import { 
  IconAB,
  IconAB2, 
  IconABOff,
  IconAbacus,
  IconAbacusOff,
  IconAbc,
  IconAccessPoint,
  IconAccessPointOff,
  IconAccessible,
  IconAccessibleFilled,
  IconAccessibleOff,
  IconActivity,
  IconActivityHeartbeat,
  IconAd2,
  IconAdCircleOff
} from "@tabler/icons-react";
import { __ } from "@wordpress/i18n";

export const tablerIcons = [
  {
    name: 'a-b-2',
    title: __('a-b-2', 'bloomedge'),
    icon: IconAB2,
    style: 'outline',
    categories: ['others'],
  },
  {
    name: 'a-b-off',
    title: __('a-b-off', 'bloomedge'),
    icon: IconABOff,
    style: 'outline',
    categories: ['others'],
  },
  {
    name: 'a-b',
    title: __('a-b', 'bloomedge'),
    icon: IconAB,
    style: 'outline',
    categories: ['others'],
  },
  {
    name: 'abacus-off',
    title: __('abacus-off', 'bloomedge'),
    icon: IconAbacusOff,
    style: 'outline',
    categories: ['math'],
  },
  {
    name: 'abacus',
    title: __('abacus', 'bloomedge'),
    icon: IconAbacus,
    style: 'outline',
    categories: ['math'],
  },
  {
    name: 'abc',
    title: __('abc', 'bloomedge'),
    icon: IconAbc,
    style: 'outline',
    categories: ['letters'],
  },
  {
    name: 'access-point-off',
    title: __('access-point-off', 'bloomedge'),
    icon: IconAccessPointOff,
    style: 'outline',
    categories: ['network', 'wireless'],
  },
  {
    name: 'access-point',
    title: __('access-point', 'bloomedge'),
    icon: IconAccessPoint,
    style: 'outline',
    categories: ['network', 'wireless'],
  },
  {
    name: 'accessible-off',
    title: __('accessible-off', 'bloomedge'),
    icon: IconAccessibleOff,
    style: 'outline',
    categories: ['others'],
  },
  {
    name: 'accessible',
    title: __('accessible', 'bloomedge'),
    icon: IconAccessible,
    style: 'outline',
    categories: ['others'],
  },
  {
    name: 'accessible-filled',
    title: __('accessible-filled', 'bloomedge'),
    icon: IconAccessibleFilled,
    style: 'filled',
    categories: ['others'],
  },
  {
    name: 'activity-heartbeat',
    title: __('activity-heartbeat', 'bloomedge'),
    icon: IconActivityHeartbeat,
    style: 'outline',
    categories: ['health'],
  },
  {
    name: 'activity',
    title: __('activity', 'bloomedge'),
    icon: IconActivity,
    style: 'outline',
    categories: ['health'],
  },
  {
    name: 'ad-2',
    title: __('ad-2', 'bloomedge'),
    icon: IconAd2,
    style: 'outline',
    categories: ['marketing', 'commercial'],
  },
  {
    name: 'ad-circle-off',
    title: __('ad-circle-off', 'bloomedge'),
    icon: IconAdCircleOff,
    style: 'outline',
    categories: ['marketing'],
  },
]