import {
	ArchiveBroken,
	ArchiveCheckBroken,
	ArchiveDownBroken,
	ArchiveDownMinimalisticBroken,
	ArchiveUpBroken,
	ArchiveUpMinimalisticBroken,
	ClipboardAddBroken,
	ClipboardBroken,
	ClipboardCheckBroken,
	ClipboardHeartBroken,
	ClipboardListBroken,
	ClipboardRemoveBroken,
	ClipboardTextBroken,
	NotebookBroken,
	NotesBroken,
	NotesDocumentAddBroken,
	NotesDocumentBroken,
	NotesDocumentMedicineBroken,
	NotesDocumentMinimalisticBroken,
	NotesDocumentTextBroken,
	NotesDocumentsBroken,
	NotesMinimalisticBroken,
	NotificationBellBingBold,
	NotificationBellBingBoldDuotone,
	NotificationBellBingBroken,
	NotificationBellBingLineDuotone,
	NotificationBellBingOutline,
	NotificationBellBold,
	NotificationBellBoldDuotone,
	NotificationBellBroken,
	NotificationBellLineDuotone,
	NotificationBellOffBold,
	NotificationBellOffBoldDuotone,
	NotificationBellOffBroken,
	NotificationBellOffLineDuotone,
	NotificationBellOffOutline,
	NotificationBellOutline,
	NotificationLinesRemoveBold,
	NotificationLinesRemoveBoldDuotone,
	NotificationLinesRemoveBroken,
	NotificationLinesRemoveLineDuotone,
	NotificationLinesRemoveOutline,
	NotificationRemoveBold,
	NotificationRemoveBoldDuotone,
	NotificationRemoveBroken,
	NotificationRemoveLineDuotone,
	NotificationRemoveOutline,
	NotificationUnreadBold,
	NotificationUnreadBoldDuotone,
	NotificationUnreadBroken,
	NotificationUnreadLineDuotone,
	NotificationUnreadLinesBold,
	NotificationUnreadLinesBoldDuotone,
	NotificationUnreadLinesBroken,
	NotificationUnreadLinesLineDuotone,
	NotificationUnreadLinesOutline,
	NotificationUnreadOutline,
} from "./index";

export const SolarIconData = [
	{
		isDefault: true,
		name: "notification-unread-broken",
		title: "Unread",
		icon: NotificationUnreadBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-broken",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-broken",
		title: "Remove",
		icon: NotificationRemoveBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-broken",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-broken",
		title: "Bell",
		icon: NotificationBellBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-broken",
		title: "Bell Bing",
		icon: NotificationBellBingBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-broken",
		title: "Bell Off",
		icon: NotificationBellOffBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-line-duotone",
		title: "Unread",
		icon: NotificationUnreadLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-line-duotone",
		title: "Unread Lines",
		icon: NotificationUnreadLinesLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-line-duotone",
		title: "Remove",
		icon: NotificationRemoveLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-line-duotone",
		title: "Lines Remove",
		icon: NotificationLinesRemoveLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-line-duotone",
		title: "Bell",
		icon: NotificationBellLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-line-duotone",
		title: "Bell Bing",
		icon: NotificationBellBingLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-line-duotone",
		title: "Bell Off",
		icon: NotificationBellOffLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-outline",
		title: "Unread",
		icon: NotificationUnreadOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-outline",
		title: "Unread Lines",
		icon: NotificationUnreadLinesOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-outline",
		title: "Remove",
		icon: NotificationRemoveOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-outline",
		title: "Lines Remove",
		icon: NotificationLinesRemoveOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-outline",
		title: "Bell",
		icon: NotificationBellOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-outline",
		title: "Bell Bing",
		icon: NotificationBellBingOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-outline",
		title: "Bell Off",
		icon: NotificationBellOffOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-bold",
		title: "Unread",
		icon: NotificationUnreadBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-bold",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-bold",
		title: "Remove",
		icon: NotificationRemoveBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-bold",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bold",
		title: "Bell",
		icon: NotificationBellBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-bold",
		title: "Bell Bing",
		icon: NotificationBellBingBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-bold",
		title: "Bell Off",
		icon: NotificationBellOffBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-bold-duotone",
		title: "Unread",
		icon: NotificationUnreadBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-bold-duotone",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-bold-duotone",
		title: "Remove",
		icon: NotificationRemoveBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-bold-duotone",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bold-duotone",
		title: "Bell",
		icon: NotificationBellBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-bold-duotone",
		title: "Bell Bing",
		icon: NotificationBellBingBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-bold-duotone",
		title: "Bell Off",
		icon: NotificationBellOffBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-check-broken",
		title: "Archive Check",
		icon: ArchiveCheckBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-down-minimalistic-broken",
		title: "Archive Down Minimalistic",
		icon: ArchiveDownMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-down-broken",
		title: "Archive Down",
		icon: ArchiveDownBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-up-minimalistic-broken",
		title: "Archive Up Minimalistic",
		icon: ArchiveUpMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-up-broken",
		title: "Archive Up",
		icon: ArchiveUpBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-broken",
		title: "Archive",
		icon: ArchiveBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-add-broken",
		title: "Clipboard Add",
		icon: ClipboardAddBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-check-broken",
		title: "Clipboard Check",
		icon: ClipboardCheckBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-heart-broken",
		title: "Clipboard Heart",
		icon: ClipboardHeartBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-list-broken",
		title: "Clipboard List",
		icon: ClipboardListBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-remove-broken",
		title: "Clipboard Remove",
		icon: ClipboardRemoveBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-text-broken",
		title: "Clipboard Text",
		icon: ClipboardTextBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-broken",
		title: "Clipboard",
		icon: ClipboardBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-add-broken",
		title: "Document Add",
		icon: NotesDocumentAddBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-medicine-broken",
		title: "Document Medicine",
		icon: NotesDocumentMedicineBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-minimalistic-broken",
		title: "Document Minimalistic",
		icon: NotesDocumentMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-text-broken",
		title: "Document Text",
		icon: NotesDocumentTextBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-broken",
		title: "Document",
		icon: NotesDocumentBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "documents-broken",
		title: "Documents",
		icon: NotesDocumentsBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notebook-broken",
		title: "Notebook",
		icon: NotebookBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notes-minimalistic-broken",
		title: "Notes Minimalistic",
		icon: NotesMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notes-broken",
		title: "Notes",
		icon: NotesBroken,
		categories: ["notes"],
		library: "solar",
	},
];
