import {
	ArchiveBroken,
	ArchiveCheckBroken,
	ArchiveDownBroken,
	ArchiveDownMinimalisticBroken,
	ArchiveUpBroken,
	ArchiveUpMinimalisticBroken,
	ArrowToDownLeftBroken,
	ArrowToDownRightBroken,
	ArrowToTopLeftBroken,
	ArrowToTopRightBroken,
	CircleBottomDownBroken,
	CircleBottomUpBroken,
	CircleTopDownBroken,
	ClipboardAddBroken,
	ClipboardBroken,
	ClipboardCheckBroken,
	ClipboardHeartBroken,
	ClipboardListBroken,
	ClipboardRemoveBroken,
	ClipboardTextBroken,
	DownloadBroken,
	DownloadMinimalisticBroken,
	DownloadSquareBroken,
	DownloadTwiceSquareBroken,
	ExitBroken,
	ExportBroken,
	ForwardAltBroken,
	ForwardBroken,
	ImportBroken,
	Login2Broken,
	LoginAltBroken,
	LoginBroken,
	Logout2Broken,
	LogoutAltBroken,
	LogoutBroken,
	MaximizeBroken,
	MaximizeSquare2Broken,
	MaximizeSquare3Broken,
	MaximizeSquareBroken,
	MaximizeSquareMinimalisticBroken,
	MinimizeBroken,
	MinimizeSquare2Broken,
	MinimizeSquare3Broken,
	MinimizeSquareBroken,
	MinimizeSquareMinimalisticBroken,
	NotebookBroken,
	NotesBroken,
	NotesDocumentAddBroken,
	NotesDocumentBroken,
	NotesDocumentMedicineBroken,
	NotesDocumentMinimalisticBroken,
	NotesDocumentTextBroken,
	NotesDocumentsBroken,
	NotesMinimalisticBroken,
	NotificationBellBingBold,
	NotificationBellBingBoldDuotone,
	NotificationBellBingBroken,
	NotificationBellBingLineDuotone,
	NotificationBellBingOutline,
	NotificationBellBold,
	NotificationBellBoldDuotone,
	NotificationBellBroken,
	NotificationBellLineDuotone,
	NotificationBellOffBold,
	NotificationBellOffBoldDuotone,
	NotificationBellOffBroken,
	NotificationBellOffLineDuotone,
	NotificationBellOffOutline,
	NotificationBellOutline,
	NotificationLinesRemoveBold,
	NotificationLinesRemoveBoldDuotone,
	NotificationLinesRemoveBroken,
	NotificationLinesRemoveLineDuotone,
	NotificationLinesRemoveOutline,
	NotificationRemoveBold,
	NotificationRemoveBoldDuotone,
	NotificationRemoveBroken,
	NotificationRemoveLineDuotone,
	NotificationRemoveOutline,
	NotificationUnreadBold,
	NotificationUnreadBoldDuotone,
	NotificationUnreadBroken,
	NotificationUnreadLineDuotone,
	NotificationUnreadLinesBold,
	NotificationUnreadLinesBoldDuotone,
	NotificationUnreadLinesBroken,
	NotificationUnreadLinesLineDuotone,
	NotificationUnreadLinesOutline,
	NotificationUnreadOutline,
	ReOrderBroken,
	ReceiveSquareBroken,
	ReceiveTwiceSquareBroken,
	ReplayAltBroken,
	ReplayBroken,
	ScaleBroken,
	ScreenShareBroken,
	SendSquareBroken,
	SendTwiceSquareBroken,
	SquareBottomDownBroken,
	SquareBottomUpBroken,
	SquareTopDownBroken,
	SquareTopUpBroken,
	UndoLeftBroken,
	UndoLeftRoundBroken,
	UndoLeftRoundSquareBroken,
	UndoLeftSquareBroken,
	UndoRightRoundBroken,
	UndoRightRoundSquareBroken,
	UndoRightSquareBroken,
	UploadBroken,
	UploadMinimalisticBroken,
	UploadSquareBroken,
	UploadTwiceSquareBroken,
} from "./index";

export const SolarIconData = [
	{
		isDefault: true,
		name: "notification-unread-broken",
		title: "Unread",
		icon: NotificationUnreadBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-broken",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-broken",
		title: "Remove",
		icon: NotificationRemoveBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-broken",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-broken",
		title: "Bell",
		icon: NotificationBellBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-broken",
		title: "Bell Bing",
		icon: NotificationBellBingBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-broken",
		title: "Bell Off",
		icon: NotificationBellOffBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-line-duotone",
		title: "Unread",
		icon: NotificationUnreadLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-line-duotone",
		title: "Unread Lines",
		icon: NotificationUnreadLinesLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-line-duotone",
		title: "Remove",
		icon: NotificationRemoveLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-line-duotone",
		title: "Lines Remove",
		icon: NotificationLinesRemoveLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-line-duotone",
		title: "Bell",
		icon: NotificationBellLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-line-duotone",
		title: "Bell Bing",
		icon: NotificationBellBingLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-line-duotone",
		title: "Bell Off",
		icon: NotificationBellOffLineDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-outline",
		title: "Unread",
		icon: NotificationUnreadOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-outline",
		title: "Unread Lines",
		icon: NotificationUnreadLinesOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-outline",
		title: "Remove",
		icon: NotificationRemoveOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-outline",
		title: "Lines Remove",
		icon: NotificationLinesRemoveOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-outline",
		title: "Bell",
		icon: NotificationBellOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-outline",
		title: "Bell Bing",
		icon: NotificationBellBingOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-outline",
		title: "Bell Off",
		icon: NotificationBellOffOutline,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-bold",
		title: "Unread",
		icon: NotificationUnreadBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-bold",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-bold",
		title: "Remove",
		icon: NotificationRemoveBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-bold",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bold",
		title: "Bell",
		icon: NotificationBellBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-bold",
		title: "Bell Bing",
		icon: NotificationBellBingBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-bold",
		title: "Bell Off",
		icon: NotificationBellOffBold,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-bold-duotone",
		title: "Unread",
		icon: NotificationUnreadBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-bold-duotone",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-bold-duotone",
		title: "Remove",
		icon: NotificationRemoveBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-bold-duotone",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bold-duotone",
		title: "Bell",
		icon: NotificationBellBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-bold-duotone",
		title: "Bell Bing",
		icon: NotificationBellBingBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-bold-duotone",
		title: "Bell Off",
		icon: NotificationBellOffBoldDuotone,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-check-broken",
		title: "Archive Check",
		icon: ArchiveCheckBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-down-minimalistic-broken",
		title: "Archive Down Minimalistic",
		icon: ArchiveDownMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-down-broken",
		title: "Archive Down",
		icon: ArchiveDownBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-up-minimalistic-broken",
		title: "Archive Up Minimalistic",
		icon: ArchiveUpMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-up-broken",
		title: "Archive Up",
		icon: ArchiveUpBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "archive-broken",
		title: "Archive",
		icon: ArchiveBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-add-broken",
		title: "Clipboard Add",
		icon: ClipboardAddBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-check-broken",
		title: "Clipboard Check",
		icon: ClipboardCheckBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-heart-broken",
		title: "Clipboard Heart",
		icon: ClipboardHeartBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-list-broken",
		title: "Clipboard List",
		icon: ClipboardListBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-remove-broken",
		title: "Clipboard Remove",
		icon: ClipboardRemoveBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-text-broken",
		title: "Clipboard Text",
		icon: ClipboardTextBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "clipboard-broken",
		title: "Clipboard",
		icon: ClipboardBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-add-broken",
		title: "Document Add",
		icon: NotesDocumentAddBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-medicine-broken",
		title: "Document Medicine",
		icon: NotesDocumentMedicineBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-minimalistic-broken",
		title: "Document Minimalistic",
		icon: NotesDocumentMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-text-broken",
		title: "Document Text",
		icon: NotesDocumentTextBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "document-broken",
		title: "Document",
		icon: NotesDocumentBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "documents-broken",
		title: "Documents",
		icon: NotesDocumentsBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notebook-broken",
		title: "Notebook",
		icon: NotebookBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notes-minimalistic-broken",
		title: "Notes Minimalistic",
		icon: NotesMinimalisticBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notes-broken",
		title: "Notes",
		icon: NotesBroken,
		categories: ["notes"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "arrow-to-down-left-broken",
		title: "Arrow To Down Left",
		icon: ArrowToDownLeftBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "arrow-to-down-right-broken",
		title: "Arrow To Down Right",
		icon: ArrowToDownRightBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "arrow-to-top-left-broken",
		title: "Arrow To Top Left",
		icon: ArrowToTopLeftBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "arrow-to-top-right-broken",
		title: "Arrow To Top Right",
		icon: ArrowToTopRightBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "circle-bottom-down-broken",
		title: "Circle Bottom Down",
		icon: CircleBottomDownBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "circle-bottom-up-broken",
		title: "Circle Bottom Up",
		icon: CircleBottomUpBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "circle-top-down-broken",
		title: "Circle Top Down",
		icon: CircleTopDownBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "download-minimalistic-broken",
		title: "Download Minimalistic",
		icon: DownloadMinimalisticBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "download-square-broken",
		title: "Download Square",
		icon: DownloadSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "download-twice-square-broken",
		title: "Download Twice Square",
		icon: DownloadTwiceSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "download-broken",
		title: "Download",
		icon: DownloadBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "exit-broken",
		title: "Exit",
		icon: ExitBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "export-broken",
		title: "Export",
		icon: ExportBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "forward-alt-broken",
		title: "Forward Alt",
		icon: ForwardAltBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "forward-broken",
		title: "Forward",
		icon: ForwardBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "import-broken",
		title: "Import",
		icon: ImportBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "login-broken",
		title: "Login",
		icon: LoginBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "login-alt-broken",
		title: "Login Alt",
		icon: LoginAltBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "login-2-broken",
		title: "Login 2",
		icon: Login2Broken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "logout-broken",
		title: "Logout",
		icon: LogoutBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "logout-alt-broken",
		title: "Logout Alt",
		icon: LogoutAltBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "logout-2-broken",
		title: "Logout 2",
		icon: Logout2Broken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "maximize-broken",
		title: "Maximize",
		icon: MaximizeBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "maximize-square-broken",
		title: "Maximize Square",
		icon: MaximizeSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "maximize-square-2-broken",
		title: "Maximize Square 2",
		icon: MaximizeSquare2Broken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "maximize-square-3-broken",
		title: "Maximize Square 3",
		icon: MaximizeSquare3Broken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "maximize-square-minimalistic-broken",
		title: "Maximize Square Minimalistic",
		icon: MaximizeSquareMinimalisticBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "minimize-broken",
		title: "Minimize",
		icon: MinimizeBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "minimize-square-broken",
		title: "Minimize Square",
		icon: MinimizeSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "minimize-square-2-broken",
		title: "Minimize Square 2",
		icon: MinimizeSquare2Broken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "minimize-square-3-broken",
		title: "Minimize Square 3",
		icon: MinimizeSquare3Broken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "minimize-square-minimalistic-broken",
		title: "Minimize Square Minimalistic",
		icon: MinimizeSquareMinimalisticBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "receive-square-broken",
		title: "Receive Square",
		icon: ReceiveSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "receive-twice-square-broken",
		title: "Receive Twice Square",
		icon: ReceiveTwiceSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "reorder-broken",
		title: "Reorder",
		icon: ReOrderBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "replay-broken",
		title: "Replay",
		icon: ReplayBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "replay-alt-broken",
		title: "Replay Alt",
		icon: ReplayAltBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "scale-broken",
		title: "Scale",
		icon: ScaleBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "screen-share-broken",
		title: "Screen Share",
		icon: ScreenShareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "send-square-broken",
		title: "Send Square",
		icon: SendSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "send-twice-square-broken",
		title: "Send Twice Square",
		icon: SendTwiceSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "square-bottom-down-broken",
		title: "Square Bottom Down",
		icon: SquareBottomDownBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "square-bottom-up-broken",
		title: "Square Bottom Up",
		icon: SquareBottomUpBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "square-top-down-broken",
		title: "Square Top Down",
		icon: SquareTopDownBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "square-top-up-broken",
		title: "Square Top Up",
		icon: SquareTopUpBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-left-round-square-broken",
		title: "Undo Left Round Square",
		icon: UndoLeftRoundSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-left-round-broken",
		title: "Undo Left Round",
		icon: UndoLeftRoundBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-left-square-broken",
		title: "Undo Left Square",
		icon: UndoLeftSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-left-broken",
		title: "Undo Left",
		icon: UndoLeftBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-right-round-square-broken",
		title: "Undo Right Round Square",
		icon: UndoRightRoundSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-right-round-broken",
		title: "Undo Right Round",
		icon: UndoRightRoundBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "undo-right-square-broken",
		title: "Undo Right Square",
		icon: UndoRightSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "upload-minimalistic-broken",
		title: "Upload Minimalistic",
		icon: UploadMinimalisticBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "upload-square-broken",
		title: "Upload Square",
		icon: UploadSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "upload-twice-square-broken",
		title: "Upload Twice Square",
		icon: UploadTwiceSquareBroken,
		categories: ["arrows"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "upload-broken",
		title: "Upload",
		icon: UploadBroken,
		categories: ["arrows"],
		library: "solar",
	},
];
