import {
	NotificationBellBingBroken,
	NotificationBellBroken,
	NotificationBellOffBroken,
	NotificationLinesRemoveBroken,
	NotificationRemoveBroken,
	NotificationUnreadBroken,
	NotificationUnreadLinesBroken,
} from "./index";

export const SolarIconData = [
	{
		isDefault: true,
		name: "notification-unread-broken",
		title: "Unread",
		icon: NotificationUnreadBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-unread-lines-broken",
		title: "Unread Lines",
		icon: NotificationUnreadLinesBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-remove-broken",
		title: "Remove",
		icon: NotificationRemoveBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-lines-remove-broken",
		title: "Lines Remove",
		icon: NotificationLinesRemoveBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-broken",
		title: "Bell",
		icon: NotificationBellBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-bing-broken",
		title: "Bell Bing",
		icon: NotificationBellBingBroken,
		categories: ["notification"],
		library: "solar",
	},
	{
		isDefault: true,
		name: "notification-bell-off-broken",
		title: "Bell Off",
		icon: NotificationBellOffBroken,
		categories: ["notification"],
		library: "solar",
	},
];
